### ISSUE TITLE
Android app keeps dropping the model after first inference 

### ISSUE THREAD

**Issue by patrickmac110** [MaidFoundation/maid#184] opened 2023-12-04 13:14 UTC
First off, this app is great, so thank you for creating something like this!
But the issue, once I load the model and go into my session, after I enter a prompt and it finishes the first response, I'll go to respond and it'll give me a pop-up saying to choose a model. I'll then choose a model, hit the back arrow at the top of the screen, but I'll still get the same message when I try to respond. And when it inevitably takes me back to the model settings page, there's no model loaded. Even if I load a model, go back to my chat window, and then go back to the model settings, the model isn't loaded. 

I'm on an unrooted Pixel 7 Pro, if that matters. With 11gb of RAM. And the latest version of the app.

**Comment by danemadsen** [comment] 2023-12-04 23:26
Hmm, OK it seems like 2 things are happening here that ill have to look at. 
1. The main issue is the model is being dropped after generation
2. Once you reset the model in the model menu the local generation is also reset (This is expected behavior for now as any time you navigate away from the chat page the local generation is reset).

Ive encountered a lot of issues like this since Ive switched to using providers for state management so that's probably whats causing the issue

**Comment by Skldude** [comment] 2023-12-05 00:18
Id also just like to add my 2 cents, im on pixel 7 not pro 7gb ram.

1.1.3 crashes out after prompting for the first time anything over a 3B model.

1.1.2 crashes out after prompting any model for the first time.

1.1.1 and 1.1.0 work with anything up to 7B but are considerably slower than 1.0.9. which is the current version I'm using because of the speed and the reliability. 

Normal bugs I come across are that if I scroll down while the text is streaming it bugs out and goes back to the typing animation and doesn't regenerate, and changing basically any of the parameters results in a crash when prompting. 

Not really looking for solutions just wanted to give feedback.

**Comment by danemadsen** [comment] 2023-12-05 12:11
do me a favor and try this build:
https://github.com/MaidFoundation/maid/actions/runs/7100132850

it should be fixed now

**Comment by LordMajestros** [comment] 2023-12-07 06:10
Can you put out a new release with this fix? I'm away from my desk for a week and can't build it for testing

**Comment by LordMajestros** [comment] 2023-12-07 11:41
I switched browsers and it's working now. Thanks.

**Closed** 2023-12-08 12:46 UTC
