### ISSUE TITLE
Scroll bug

### ISSUE THREAD

**Issue by GameOverFlowChart** [MaidFoundation/maid#200] opened 2023-12-07 15:09 UTC
I found a bug which is apparently reproducible.
Step one, have a longer conversation. Step 2: while the model is outputing text, scroll up (the output must be out of sight) and back down. That's it, now the text box reverted to the three dots and is stuck in this state.

**Comment by danemadsen** [comment] 2023-12-07 21:24
Yeah I did have this fixed in an earlier version but it seems to have come back.

**Closed** 2023-12-08 12:44 UTC

**Comment by danemadsen** [comment] 2023-12-08 12:51
@GameOverFlowChart ok give the build here a go

https://github.com/MaidFoundation/maid/actions/runs/7141484360

the issue should be fixed now

**Comment by GameOverFlowChart** [comment] 2023-12-08 13:25
> @GameOverFlowChart ok give the build here a go
> 
> https://github.com/MaidFoundation/maid/actions/runs/7141484360
> 
> the issue should be fixed now

So the 3 dot problem is solved. There seems to still be some problems related which I don't fully understand yet. First it was like the output stopped at one point but the send button didn't change color. But there seems also to be a (temporal?) Problem clashing with the regenerate function. If you branch out with regenerate, and scroll up and down, the text can be replaced with an answer from another bramch or something? 
Overall this version is better because you don't get stuck with the 3 dots and the other problems seem to not happen always. Maybe if I understand the other problems better I can open a new issue.

**Comment by danemadsen** [comment] 2023-12-08 13:44
Yeah the issue is due to the message widgets being disposed of when you scroll away from them. When dispose is called the stream controllers are closed leading to errors where the generation manager tries to write data to a closed stream which is what caused the original error with the 3 dots. Now I've mitigated it by using a buffer when the widget is off screen but there's definitely potential for errors caused by branches.

In the past this issue was mitigated by simply locking the scroll when a a generation is in progress but that's just not a very clean way to do things.
