### ISSUE TITLE
Poor performance and crashes when using certain models

### ISSUE THREAD

**Issue by Skldude** [MaidFoundation/maid#185] opened 2023-12-05 00:24 UTC
Im on pixel 7 not pro 7gb ram.

1.1.3 crashes out after prompting for the first time anything over a 3B model.

1.1.2 crashes out after prompting any model for the first time.

1.1.1 and 1.1.0 work with anything up to 7B but are considerably slower than 1.0.9. which is the current version I'm using because of the speed and the reliability.

Normal bugs I come across are that if I scroll down while the text is streaming it bugs out and goes back to the typing animation and doesn't regenerate, and changing basically any of the parameters results in a crash when prompting.

Just wanted to give feedback.

**Comment by danemadsen** [comment] 2023-12-05 02:26
yeah Ive noticed the same regressions. Not sure whats causing it other than newer llama.cpp versions? Very little c++ code has changed since 1.0.9 so not really sure whats causing the slowdowns / instability? I might test out rolling back to whatever version of llama.cpp 1.0.9 is on.

**Comment by danemadsen** [comment] 2023-12-05 02:57
you can view the difference here to help diagnose the issue if you like:

https://github.com/MaidFoundation/maid/compare/1.0.9...1.1.3

**Comment by danemadsen** [comment] 2023-12-07 11:33
@Skldude Ok ive rolled back to the llama.cpp version 1.0.9 was using. It seems to be more stable and runs 7b models on my devices if you could give it a try that would be helpful. try these builds when you get a chance:

https://github.com/MaidFoundation/maid/actions/runs/7127583201

**Comment by Skldude** [comment] 2023-12-07 19:44
@danemadsen Hey been messing around with this a little this morning, 7B models are working again and seems just as fast as version 1.0.9 . Also the crashing issue when changing the preferences from 1.0.9 seems to have been fixed as well.

**Comment by danemadsen** [comment] 2023-12-07 21:05
> @danemadsen Hey been messing around with this a little this morning, 7B models are working again and seems just as fast as version 1.0.9 . Also the crashing issue when changing the preferences from 1.0.9 seems to have been fixed as well.

Yeah, unfortunately it seems to be an issue with llama.cpp

**Comment by RookieIndieDev** [comment] 2023-12-09 05:02
1B models, some of them work on my device but some others still cause crashes. This one example: [Akins 3b](https://huggingface.co/TheBloke/Akins-3B-GGUF)

**Comment by sfiannaca** [comment] 2023-12-09 08:39
I found that using the 1.0.6 release, both the 3b Orca Mini and 1B TinyLama work significantly faster than they do currently

**Comment by dillfrescott** [comment] 2023-12-09 11:02
The new Stablelm zephyr 3B causes the app to close on me

**Comment by Skldude** [comment] 2023-12-09 20:19
Same here. New models seem to crash the app immediately

**Comment by danemadsen** [comment] 2023-12-10 00:17
@RookieIndieDev @sfiannaca @dillfrescott @Skldude In testing it seems alot of the crashes are related to the algorithm I'm using to remove input prefix and suffix's. For testing to see if your models works you should turn off interactive in the model settings.

**Comment by dillfrescott** [comment] 2023-12-10 02:14
@danemadsen Thanks for the tip. This will help until an actual fix is implemented.

**Comment by RookieIndieDev** [comment] 2023-12-10 04:41
It still crashes even after disabling interactive mode.

**Comment by danemadsen** [comment] 2023-12-10 07:33
OK, this build seems to be much more stable with all the models I've tested (Llama 7b Chat, Xwin-7B, Calypso 4b, Mistral 7B, OrcaMini)

https://github.com/MaidFoundation/maid/actions/runs/7156351399

**Comment by danemadsen** [comment] 2023-12-11 12:23
Unless someone is still having problems with a model i'm closing this issue

**Closed by danemadsen** 2023-12-11 12:23 UTC
Labels: bug
